# Generated by Django 5.0.6 on 2025-03-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cdetail',
            fields=[
                ('unique', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('mail', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('passw', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('service', models.JSONField(default=list)),
            ],
        ),
    ]
