# Generated by Django 5.0.6 on 2025-03-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csdata', '0003_alter_ticket_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('unique', models.AutoField(primary_key=True, serialize=False)),
                ('profile_image', models.URLField(max_length=500)),
                ('name', models.CharField(max_length=70)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.TextField(max_length=1000)),
                ('service_provided', models.CharField(max_length=500)),
                ('experience', models.PositiveIntegerField()),
                ('specialization', models.CharField(max_length=800)),
                ('description', models.TextField()),
                ('no_of_service_provided', models.IntegerField()),
            ],
        ),
    ]
