# Generated by Django 5.0.6 on 2025-03-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csdata', '0006_alter_employee_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='employee',
            name='description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_image',
            field=models.URLField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='employee',
            name='specialization',
            field=models.CharField(max_length=1000),
        ),
    ]
