# Generated by Django 5.0.6 on 2025-03-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csdata', '0007_alter_employee_address_alter_employee_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_image',
            field=models.CharField(max_length=3000),
        ),
    ]
