# Generated by Django 5.0.6 on 2025-03-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csdata', '0008_alter_employee_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdetail',
            name='profile_image',
            field=models.CharField(default='default.jpg', max_length=4000),
            preserve_default=False,
        ),
    ]
