# Generated by Django 5.0.6 on 2025-03-22 13:28

import csdata.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csdata', '0009_cdetail_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdetail',
            name='profile_image',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='cdetail',
            name='service',
            field=models.JSONField(default=csdata.models.get_default_service),
        ),
    ]
