# Generated by Django 5.0.6 on 2025-03-22 13:34

import csdata.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csdata', '0010_alter_cdetail_profile_image_alter_cdetail_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdetail',
            name='service',
            field=models.JSONField(blank=True, default=csdata.models.get_default_service, null=True),
        ),
    ]
