# Generated by Django 5.0.6 on 2025-03-24 08:52

import csdata.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csdata', '0011_alter_cdetail_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdetail',
            name='servicehistory',
            field=models.JSONField(blank=True, default=csdata.models.get_default_service, null=True),
        ),
    ]
