# Generated by Django 5.0.6 on 2025-03-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csdata', '0012_cdetail_servicehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('unique', models.AutoField(primary_key=True, serialize=False)),
                ('uniqueuser', models.IntegerField(max_length=5)),
                ('uniqueservice', models.IntegerField(max_length=5)),
                ('advance', models.BooleanField()),
            ],
        ),
    ]
