# Generated by Django 5.0.6 on 2025-03-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csdata', '0013_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='uniqueservice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='uniqueuser',
            field=models.IntegerField(),
        ),
    ]
