# Generated by Django 5.0.6 on 2025-03-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csdata', '0014_alter_bookings_uniqueservice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='advance',
            field=models.BooleanField(default=False),
        ),
    ]
