# Generated by Django 5.0.6 on 2025-03-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csdata', '0015_alter_bookings_advance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='email',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
