# Generated by Django 5.0.6 on 2025-03-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csdata', '0016_bookings_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdetail',
            name='service',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
